"""Pydantic models for MCP inputs and outputs."""

from es_mcp_server.models.common import ErrorResponse, ErrorType, StrictModel
from es_mcp_server.models.kibana import (
    KibanaDashboardReferencesRequest,
    KibanaDashboardReferencesResponse,
    KibanaDashboardRequest,
    KibanaDashboardResponse,
    KibanaDashboardSummary,
    KibanaListDashboardsRequest,
    KibanaListDashboardsResponse,
    KibanaSpacesRequest,
    KibanaSpacesResponse,
    KibanaStatusRequest,
    KibanaStatusResponse,
)
from es_mcp_server.models.tools import (
    ClusterHealthRequest,
    DslSearchRequest,
    ErrorTrendsRequest,
    IndexMappingRequest,
    IndexSettingsRequest,
    ListIndicesRequest,
    NodesSummaryRequest,
    RecentLogsRequest,
    SearchRequest,
    ShardAllocationRequest,
    SlowQueriesRequest,
    SnapshotStatusRequest,
)

__all__ = [
    "ClusterHealthRequest",
    "DslSearchRequest",
    "ErrorResponse",
    "ErrorTrendsRequest",
    "ErrorType",
    "IndexMappingRequest",
    "IndexSettingsRequest",
    "KibanaDashboardReferencesRequest",
    "KibanaDashboardReferencesResponse",
    "KibanaDashboardRequest",
    "KibanaDashboardResponse",
    "KibanaDashboardSummary",
    "KibanaListDashboardsRequest",
    "KibanaListDashboardsResponse",
    "KibanaSpacesRequest",
    "KibanaSpacesResponse",
    "KibanaStatusRequest",
    "KibanaStatusResponse",
    "ListIndicesRequest",
    "NodesSummaryRequest",
    "RecentLogsRequest",
    "SearchRequest",
    "ShardAllocationRequest",
    "SlowQueriesRequest",
    "SnapshotStatusRequest",
    "StrictModel",
]
